### ISSUE TITLE
[Android] Exceptions and crashes when trying to invoke stopRecording

### ISSUE THREAD

**Issue by SchneiderOr** [smartlook/smartlook-react-native-bridge#34]
Hey, i've recently implemented smartlook in one of my react-native projects,
When user moves the app to background we manually calling stopRecording and resume its recording when he brings app back to foreground.
From looking at error monitoring i can see that on Android devices there are crashes and exceptions thrown sometimes when calling RNSmartlook.stopRecording

Im attaching some of my Sentry traces

**RuntimeException com.facebook.react.bridge.JavaMethodWrapper in invoke**
Could not invoke RNSmartlook.stopRecording
exception: **JSONException: Forbidden numeric value: Infinity**
```
rg.json.JSONException: Forbidden numeric value: Infinity
    at org.json.JSON.checkDouble(JSON.java:25)
    at org.json.JSONObject.put(JSONObject.java:265)
    at a.b.a.a.f.u.g.a(SourceFile:2)
    at a.b.a.a.a.b.f.e.a(SourceFile:7)
    at a.b.a.a.f.v.e.a(SourceFile:156)
    at a.b.a.a.d.g.g.a.a(SourceFile:2984)
    at a.b.a.a.d.g.e.a(SourceFile:108)
    at a.b.a.a.d.h.a.a(SourceFile:370)
    at a.b.a.a.d.g.d.a(SourceFile:230)
    at a.b.a.a.d.e.b.f(SourceFile:6)
    at a.b.a.a.d.c.b.p(SourceFile:2)
    at com.smartlook.sdk.smartlook.Smartlook.stopRecording(SourceFile:2)
    at com.smartlook.sdk.RNSmartlookModule.stopRecording(RNSmartlookModule.java:325)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: Could not invoke RNSmartlook.stopRecording
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
```

Thanks in advance!

**Comment by krystofcelba** [comment]
Hey, sorry for waiting. We are going to release a new version after the weekend with the fix. I will inform you about that.

**Comment by SchneiderOr** [comment]
> Hey, sorry for waiting. We are going to release a new version after the weekend with the fix. I will inform you about that.

Hey, thanks for replying, we're waiting on it,
Thanks

**Comment by krystofcelba** [comment]
Hey,
we've already released version `1.2.1` with a new native Smartlook Android sdk. Anyway, you wrote that you are calling `stopRecording` manually when the app goes background. It's not needed as it's done automatically by the Smartlook SDK out of the box as well as resuming.

**Comment by SchneiderOr** [comment]
I've removed stopRecording but the automatic tracking isn't working so well, maybe its due to the fact that im using some background geolocation even when app is on background, anyway, ill upgrade and test it out
